apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Release.Name}}-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{.Release.Name}}-backend
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    resourceNames: ["{{.Release.Name}}-backend-migrations"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Release.Name}}-backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{.Release.Name}}-backend
subjects:
  - kind: ServiceAccount
    name: {{.Release.Name}}-backend
