apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-frontend
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.frontendJSReplicas}}
  selector:
    matchLabels:
      app: {{.Release.Name}}-frontend
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/frontend_cm.yml") . | sha256sum }}
      labels:
        app: {{.Release.Name}}-frontend
    spec:
      containers:
        - name: main
          image: ghcr.io/ondrejsika/counter-frontend
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{.Release.Name}}-frontend
          startupProbe:
            httpGet:
              path: /api/livez
              port: 3000
          livenessProbe:
            httpGet:
              path: /api/livez
              port: 3000
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 200Mi
